metadata:
  name: "Sucres et Lipides"
  course_title: "Sucres et Lipides"
  level: L1
  block: SANTE
  semester: S1
  subject: UE-2
  chapter: 1


inputs:
  slides_pdf: "/Users/youssefjanjar/Documents/formascience/class_parser/volume/slides/Ch1-Sucres et Lipides.pdf"
  #plan_page: 2
  # plan_pdf: "volume/plan.pdf"

outputs:
  save_json: true
  save_docx: true
  template_path: "/Users/youssefjanjar/Documents/formascience/class_parser/volume/templates/fs_template.docx"
  output_dir: "/Users/youssefjanjar/Documents/formascience/class_parser/volume/artifacts"
  test_mode: false  # Process only first 10 slides for quick testing
