metadata:
  name: "Réplication et réparation de l’ADN"
  course_title: "Réplication et réparation de l’ADN"
  level: L1
  block: SANTE
  semester: S1
  subject: UE-1
  chapter: 4


inputs:
  slides_pdf: "/Users/youssefjanjar/Documents/formascience/class_parser/volume/slides/cours_4.pdf"
  plan_pdf: "/Users/youssefjanjar/Documents/formascience/class_parser/volume/slides/cours_4_plan.pdf"
  #plan_page: 2

outputs:
  save_json: true
  save_docx: true
  template_path: "/Users/youssefjanjar/Documents/formascience/class_parser/volume/templates/fs_template.docx"
  output_dir: "/Users/youssefjanjar/Documents/formascience/class_parser/volume/artifacts"
  test_mode: false  # Process only first 10 slides for quick testing